name = "omm-api"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "api.omm.xuepoo.xyz"
custom_domain = true

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "omm-db"
database_id = "83878e93-5d64-418d-b2bc-ad9778352222"
migrations_dir = "src/db"
